# Generated by Django 4.2.4 on 2023-12-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cross_open_feedback_queries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalteam_contingent',
            name='country_code',
            field=models.CharField(default=91, max_length=5),
            preserve_default=False,
        ),
    ]
