# Generated by Django 4.2.4 on 2023-12-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_institutionalteam_contingent_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalteam_contingent',
            name='country_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
