# Generated by Django 4.2.4 on 2023-12-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_institutionalteam_contingent_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cross_open',
            name='alt_country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cross_open',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='independent_adjudicator',
            name='alt_country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='independent_adjudicator',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='institutionalteam_contingent',
            name='country_code',
            field=models.CharField(default=91, max_length=5),
            preserve_default=False,
        ),
    ]
